!<template>
    <div class="card-container">
        <div class="form-row">
            <div class="header-row">
                <div class="bold-lg cl-Mako">
                    {{ client.meta.name }}
                </div>
                <div class="pointer delete-client" @click.stop="deleteClient">
                    <adm-inline-svg
                        title="Remove"
                        :src="'delete'"
                        class="delete"
                    ></adm-inline-svg>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="flex-items">
                <nitrozen-input
                    label="Client ID"
                    :disabled="true"
                    :value="client.client_id"
                ></nitrozen-input>
                <div class="side-btn">
                    <div
                        class="pointer client-id"
                        @click="copyCode($event, client.client_id)"
                    >
                        <adm-inline-svg
                            title="Copy"
                            :src="'copy'"
                            class="copy"
                        ></adm-inline-svg>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="flex-items">
                <nitrozen-input
                    label="Client Secret"
                    :disabled="true"
                    :value="client.secret[0]"
                    :type="showSecret ? 'text' : 'password'"
                ></nitrozen-input>
                <span
                    class="password-preview"
                    @click="showSecret = !showSecret"
                >
                    <adm-inline-svg
                        :src="showSecret ? 'eye-open' : 'eye-close'"
                        class="height-20"
                    >
                    </adm-inline-svg>
                </span>
                <div class="side-btn">
                    <div
                        class="pointer client-secret"
                        @click.stop="copyCode($event, client.secret[0])"
                    >
                        <adm-inline-svg
                            title="Copy"
                            :src="'copy'"
                            class="copy"
                        ></adm-inline-svg>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="pointer cl-RoyalBlue darker-xs edit-client" @click="editClient">
                Edit
            </div>
        </div>
        <span class="cl-DustyGray2 dark-xxxxs author-details">Generated by {{this.client.author.creator_name}} on {{getTime(this.client.created_at)}}</span>
        <span class="cl-DustyGray2 dark-xxxxs author-details" v-if="isAuthorAvailable.updated_by">Updated by {{this.client.author.updator_name}} on {{getTime(this.client.modified_at)}}</span>
    </div>
</template>

<script>

import { NitrozenInput } from '@gofynd/nitrozen-vue';
import adminlinesvg from '@/components/common/adm-inline-svg.vue';
import { copyToClipboard } from '@/helper/utils';
import moment from 'moment';
export default {
    data() {
        return {
            showSecret: false,
        };
    },
    components: {
        'nitrozen-input': NitrozenInput,
        'adm-inline-svg': adminlinesvg,
    },
    props: {
        client: {
            type: Object,
            required: true,
        },
    },
    computed:{
        isAuthorAvailable(){
            return {
                "updated_by": this.client.author.updator_name ? true : false,
            }
        }
    },
    methods: {
        copyCode(event, txt) {
            copyToClipboard(txt);
            this.$snackbar.global.showInfo('Copied to clipboard', 1000);
            event.stopPropagation();
            event.preventDefault();
        },
        editClient() {
            this.$emit(
                'editOAuthClient',
                this.client.client_id
            );
        },
        deleteClient() {
            this.$emit(
                'deleteOAuthClient',
                this.client.client_id,
                this.client.meta.name
            );
        },
        getTime(time){
            return moment(new Date(time)).format('MMMM Do YYYY, h:mm:ss a')
        }
    },
};
</script>

<style lang="less" scoped>
.card-container {
    border: 1px solid @Iron;
    min-width: 350px;
    flex: 50%;
    max-width: calc(50% - 12px);
    position: relative;
    padding: 24px;
    box-sizing: border-box;
    border-radius: @BorderRadius;
    margin: 0;
    margin-bottom: 24px;

    .form-row {
        margin: 24px 0px;
        position: relative;
        .header-row {
            position: relative;
            .delete {
                position: absolute;
                top: 0;
                right: 0;
            }
        }
        .password-preview {
            cursor: pointer;
            position: relative;
            display: flex;
            height: 40px;
            transform: translateX(-10px);
            margin-left: -24px;
        }
        &:first-child {
            margin-top: 0;
        }
        &:last-child {
            margin-bottom: 0;
        }
        .pointer {
            cursor: pointer;
        }
        .link {
            cursor: pointer;
            &:hover {
                text-decoration: underline;
            }
        }
        .flex-items {
            display: flex;
            position: relative;
            align-items: flex-end;
            .nitrozen-form-input {
                flex: 1;
            }
            .side-btn {
                position: relative;
                display: flex;
                align-items: center;
                margin-left: 12px;
                height: 40px;
                width: 48px;
                div {
                    + div {
                        margin-left: 4px;
                    }
                }
                .copy {
                    width: 22px;
                }
                .delete {
                    width: 28px;
                }
                ::v-deep svg {
                    pointer-events: none;
                    width: 100%;
                    height: 100%;
                }
            }
        }
    }

    .author-details{
        display: block;
        margin: 10px 0;
    }
}
</style>