export { default as Media } from "./media.vue"   
export { default as ProductDetails } from "./details.vue"
export { default as DynamicAttributes } from "./dynamic-attributes.vue"
export { default as Customs } from "./customs.vue"
export { default as SizeGuide } from "./size-guide.vue"
