import {TABLE_COLUMN_TYPES} from "../../components/generic-graphs/data/constants";

const FILTER_KEYS = {
    EQUALS: 'is', LESS_THAN: 'lesser than', GREATER_THAN: 'greater than', LIKE: 'like',
}

const FILTER_CONDITIONS = {
    [FILTER_KEYS.EQUALS]: '=', [FILTER_KEYS.LESS_THAN]: '<', [FILTER_KEYS.GREATER_THAN]: '>', [FILTER_KEYS.LIKE]: 'like',
}
const FILTER_CONDITIONS_DROP_DOWN_DATA = Object.keys(FILTER_CONDITIONS).map(k => ({
    text: k, value: k
}))

const COLUMN_TYPE_CONDITIONS_MAPPINGS = {
    [TABLE_COLUMN_TYPES.IMAGE]: [FILTER_KEYS.LIKE],
    [TABLE_COLUMN_TYPES.NUMBER]: [FILTER_KEYS.LIKE],
    [TABLE_COLUMN_TYPES.STRING]: [FILTER_KEYS.GREATER_THAN, FILTER_KEYS.LESS_THAN],
    [TABLE_COLUMN_TYPES.GROWTH]: [FILTER_KEYS.LIKE],
}

const COLUMN_TYPE_INPUT_TYPE_MAPPINGS = {
    [TABLE_COLUMN_TYPES.IMAGE]: 'text',
    [TABLE_COLUMN_TYPES.NUMBER]: 'tel',
    [TABLE_COLUMN_TYPES.STRING]: 'text',
    [TABLE_COLUMN_TYPES.GROWTH]: 'text',
}

const TIME_FILTERS_THRESH_HOLDS = {
    MONTHLY: 30
}

const TIME_FILTERS = {
    MONTHLY: 'monthly', DAILY: 'daily'
}

const REPORTS_FILTER_MAX_STRING_LENGTH = 201
const REPORTS_FILTER_MIN_STRING_LENGTH = -1
const REPORTS_FILTER_MAX_NUMBER_LENGTH = 10 ** 11
const REPORTS_FILTER_MAX_NUMBER_DIGIT_COUNT = 11
const REPORTS_FILTER_MIN_NUMBER_LENGTH = -1

const DUPLICATE_FILTER_MESSAGE ="Duplicate Filter is not allowed"

export {
    FILTER_CONDITIONS,
    FILTER_CONDITIONS_DROP_DOWN_DATA,
    COLUMN_TYPE_CONDITIONS_MAPPINGS,
    FILTER_KEYS,
    TIME_FILTERS_THRESH_HOLDS,
    TIME_FILTERS,
    COLUMN_TYPE_INPUT_TYPE_MAPPINGS,
    REPORTS_FILTER_MAX_NUMBER_LENGTH,
    REPORTS_FILTER_MAX_STRING_LENGTH,
    REPORTS_FILTER_MIN_NUMBER_LENGTH,
    REPORTS_FILTER_MIN_STRING_LENGTH,
    REPORTS_FILTER_MAX_NUMBER_DIGIT_COUNT,
    DUPLICATE_FILTER_MESSAGE
}