export const ON_SERVER_DATA = 'ON_SERVER_DATA';

//user loggedin
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const ON_USER_LOGGED_IN = 'ON_USER_LOGGED_IN';
export const ON_USER_LOGGED_OUT = 'ON_USER_LOGGED_OUT';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const OPEN_REGISTER_MODAL = 'OPEN_REGISTER_MODAL';
export const VALIDATE_USER = 'VALIDATE_USER';
export const FETCH_ADMIN_PERMISSIONS = 'FETCH_ADMIN_PERMISSIONS';

//company-metrics
export const FETCH_METRICS = 'FETCH_METRICS';
