export const ON_SERVER_DATA = 'ON_SERVER_DATA';

//user loggedin
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const ON_USER_LOGGED_OUT = 'ON_USER_LOGGED_OUT';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const VALIDATE_USER = 'VALIDATE_USER';
export const FETCH_ADMIN_PERMISSIONS = 'FETCH_ADMIN_PERMISSIONS';

//billing
export const FETCH_CURRENT_ACTIVE_SUBSCRIPTION = 'FETCH_CURRENT_ACTIVE_SUBSCRIPTION';
export const FETCH_COMPANY_SUBSCRIPTION_LIMITS = 'FETCH_COMPANY_SUBSCRIPTION_LIMITS';

//company-metrics
export const FETCH_METRICS = 'FETCH_METRICS';

//Packaging
export const FETCH_PACKAGING_PRODUCTS = 'FETCH_PACKAGING_PRODUCTS'
export const FETCH_GROUP_CATEGORIES = 'FETCH_GROUP_CATEGORIES'
export const SAVE_CATEGORY = 'SAVE_CATEGORY'
export const SAVE_PACKAGING_PRODUCT = 'SAVE_PACKAGING_PRODUCT'
export const EDIT_CATEGORY = 'EDIT_CATEGORY'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'

export const CLEAR_PRODUCT = "CLEAR_PRODUCT"
export const CLEAR_CATEGORY = "CLEAR_CATEGORY"

export const FETCH_L3_CATEGORIES = "FETCH_L3_CATEGORIES"

export const FETCH_COMPANY_PRODUCTS = "FETCH_COMPANY_PRODUCTS"

// webhook report history actions
export const ADMIN_GET_REPORT_HISTORIES = 'ADMIN_GET_REPORT_HISTORIES';
export const ADMIN_CANCEL_WEBHOOK_REPORT = 'ADMIN_CANCEL_WEBHOOK_REPORT';
export const ADMIN_CHANGE_REPORT_HISTORY_PAGINATION = 'ADMIN_CHANGE_PAGINATION';
export const ADMIN_SET_SUBSCRIBER_ID_MAP = 'ADMIN_SET_SUBSCRIBER_ID_MAP';
export const ADMIN_SET_SUBSCRIBER_ID = 'ADMIN_SET_SUBSCRIBER_ID';
export const ADMIN_CLEAR_TO_DEFAULTS = 'ADMIN_CLEAR_TO_DEFAULTS';

//Variants
export const FETCH_VARIANTS = "FETCH_VARIANTS"
export const CREATE_EDIT_VARIANTS = "CREATE_EDIT_VARIANTS"
export const FETCH_VARIANT_DISPLAY_TYPE = "FETCH_VARIANT_DISPLAY_TYPE"
export const FETCH_TEMPLATES = "FETCH_TEMPLATES"
export const FETCH_ATTRIBUTES = "FETCH_ATTRIBUTES"