export const ON_SERVER_DATA = 'ON_SERVER_DATA';

//user loggedin
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const ON_USER_LOGGED_OUT = 'ON_USER_LOGGED_OUT';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const VALIDATE_USER = 'VALIDATE_USER';
export const FETCH_ADMIN_PERMISSIONS = 'FETCH_ADMIN_PERMISSIONS';

//billing
export const FETCH_CURRENT_ACTIVE_SUBSCRIPTION = 'FETCH_CURRENT_ACTIVE_SUBSCRIPTION';
export const FETCH_COMPANY_SUBSCRIPTION_LIMITS = 'FETCH_COMPANY_SUBSCRIPTION_LIMITS';

//company-metrics
export const FETCH_METRICS = 'FETCH_METRICS';

//Packaging
export const FETCH_PACKAGING_PRODUCTS = 'FETCH_PACKAGING_PRODUCTS'
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const SAVE_CATEGORY = 'SAVE_CATEGORY'
export const SAVE_PACKAGING_PRODUCT = 'SAVE_PACKAGING_PRODUCT'