export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const GET_USER_INFO = 'GET_USER_INFO';
export const IS_VALID_USER = 'IS_VALID_USER';
export const GET_USER_PERMISSIONS = 'GET_USER_PERMISSIONS';
export const ADMIN_PERMISSIONS = 'ADMIN_PERMISSIONS';

//billing
export const GET_CURRENT_ACTIVE_SUBSCRIPTION =
    'GET_CURRENT_ACTIVE_SUBSCRIPTION';
export const GET_COMPANY_SUBSCRIPTION_LIMITS =
    'GET_COMPANY_SUBSCRIPTION_LIMITS';

export const GET_METRICS = 'GET_METRICS';
export const GET_HELP_SECTION_DATA = 'GET_HELP_SECTION_DATA';

//packaging
export const GET_PACKAGING_PRODUCTS = 'GET_PACKAGING_PRODUCTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';

export const GET_EDIT_CATEGORY = 'GET_EDIT_CATEGORY';
export const GET_EDIT_PRODUCT = 'GET_EDIT_PRODUCT';

export const GET_L3_CATEGORIES = 'GET_L3_CATEGORIES';
export const GET_L3_DICT = 'GET_L3_DICT';

//variants
export const GET_VARIANTS = 'GET_VARIANTS'
//
export const GET_REPORT_HISTORIES = "GET_REPORT_HISTORIES";
export const GET_REPORT_HISTORY_PAGINATION = "GET_REPORT_HISTORY_PAGINATION";
export const GET_SUBSCRIBER_ID_MAP = "GET_SUBSCRIBER_ID_MAP";


//analytics
export const GET_ALL_FILTERS = "GET_ALL_FILTERS";
export const TABLE_FILTERS_SEED_DATA = "TABLE_FILTERS_SEED_DATA";
export const REPORT_SELECTED_DATE_FILTERS = "REPORT_SELECTED_DATE_FILTERS";
export const REPORT_GRAPH_FILTER_INDEX = "REPORT_GRAPH_FILTER_INDEX";
export const GET_DASHBOARD_CARD_NAV_LINK = "GET_DASHBOARD_CARD_NAV_LINK";
export const GET_IS_DEFAULT_LAYOUT_FLAG = "GET_IS_DEFAULT_LAYOUT_FLAG";
export const GET_GLOBAL_SEED_FILTERS = "GET_SEED_FILTERS";
export const GET_GLOBAL_FILTERS = "GET_GLOBAL_FILTERS";
export const GET_ADDITIONAL_FILTER_NAMES = "GET_ADDITIONAL_FILTER_NAMES";
export const GET_GLOBALLY_STAGED_FILTER = "GET_GLOBALLY_STAGED_FILTER";
export const SALES_DUMP_DOWNLOAD_STATUS = "SALES_DUMP_DOWNLOAD_STATUS";
export const SALES_DUMP_TRACKER = "SALES_DUMP_TRACKER";


//ninja
export const GET_ALL_FILTERS_NINJA = "GET_ALL_FILTERS_NINJA";
export const GET_GLOBAL_FILTERS_NINJA = "GET_GLOBAL_FILTERS_NINJA";
export const GET_GLOBAL_SEED_FILTERS_NINJA = "GET_GLOBAL_SEED_FILTERS_NINJA";
