export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const GET_USER_INFO = 'GET_USER_INFO';
export const IS_VALID_USER = 'IS_VALID_USER';
export const GET_USER_PERMISSIONS = 'GET_USER_PERMISSIONS';
export const ADMIN_PERMISSIONS = 'ADMIN_PERMISSIONS';

//billing
export const GET_CURRENT_ACTIVE_SUBSCRIPTION =
    'GET_CURRENT_ACTIVE_SUBSCRIPTION';
export const GET_COMPANY_SUBSCRIPTION_LIMITS =
    'GET_COMPANY_SUBSCRIPTION_LIMITS';

export const GET_METRICS = 'GET_METRICS';
export const GET_HELP_SECTION_DATA = 'GET_HELP_SECTION_DATA';

//packaging
export const GET_PACKAGING_PRODUCTS = 'GET_PACKAGING_PRODUCTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';

export const GET_EDIT_CATEGORY = 'GET_EDIT_CATEGORY';
export const GET_EDIT_PRODUCT = 'GET_EDIT_PRODUCT';

export const GET_L3_CATEGORIES = 'GET_L3_CATEGORIES';
export const GET_L3_DICT = 'GET_L3_DICT';

//
export const GET_REPORT_HISTORIES = "GET_REPORT_HISTORIES";
export const GET_REPORT_HISTORY_PAGINATION = "GET_REPORT_HISTORY_PAGINATION";
export const GET_SUBSCRIBER_ID_MAP = "GET_SUBSCRIBER_ID_MAP";
