export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const GET_USER_INFO = 'GET_USER_INFO';
export const IS_VALID_USER = 'IS_VALID_USER';
export const GET_USER_PERMISSIONS = 'GET_USER_PERMISSIONS';
export const ADMIN_PERMISSIONS = 'ADMIN_PERMISSIONS';

export const GET_METRICS = 'GET_METRICS';
