//user meta info
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN';
export const SET_USER_LOGGED_OUT = 'SET_USER_LOGGED_OUT';

export const SET_SERVER_DATA = 'SET_SERVER_DATA';
export const SET_USER_VALID = 'SET_USER_VALID';
export const SET_USER_PERMISSIONS = 'SET_USER_PERMISSIONS';
export const SET_ADMIN_PERMISSIONS = 'SET_ADMIN_PERMISSIONS';

//billing
export const SET_CURRENT_ACTIVE_SUBSCRIPTION =
    'SET_CURRENT_ACTIVE_SUBSCRIPTION';
export const SET_COMPANY_MAX_APPLICATIONS_LIMIT =
    'SET_COMPANY_MAX_APPLICATIONS_LIMIT';

export const UPDATE_METRICS = 'UPDATE_METRICS';

//packaging
export const SET_PACKAGING_PRODUCTS = 'SET_PACKAGING_PRODUCTS';
export const SET_CATEGORIES = 'SET_CATEGORIES';

export const SET_EDIT_CATEGORY = 'SET_EDIT_CATEGORY';
export const SET_EDIT_PRODUCT = 'SET_EDIT_PRODUCT';

export const SET_CLEAR_PRODUCT = 'SET_CLEAR_PRODUCT';
export const SET_CLEAR_CATEGORY = 'SET_CLEAR_CATEGORY';

export const SET_L3_CATEGORIES = 'SET_L3_CATEGORIES';
export const SET_L3_DICT = 'SET_L3_DICT';

// webhook
export const SET_REPORT_HISTORIES = 'SET_REPORT_HISTORIES';
export const CANCEL_REPORT = 'CANCEL_REPORT';
export const PAGINATION_CHANGE = 'PAGINATION_CHANGE';
export const SET_SUBSCRIBER_ID_MAP = 'SET_SUBSCRIBER_ID_MAP';
export const SET_SUBSCRIBER_ID = 'SET_SUBSCRIBER_ID';
export const CLEAR_STORE_TO_DEFAULT = 'CLEAR_STORE_TO_DEFAULT';
//variants
export const SET_VARIANTS = 'SET_VARIANTS'

// analytics graphs section
export const ADMIN_SET_DASHBOARD_DATA = 'ADMIN_SET_DASHBOARD_DATA'
export const ADMIN_SET_REPORT_DATA = 'ADMIN_SET_REPORT_DATA'
export const TOGGLE_LAYOUT_HEADER_GRAPH = 'TOGGLE_LAYOUT_HEADER_GRAPH'
export const LAYOUT_FOR_LARGER_DEVICE = 'LAYOUT_FOR_LARGER_DEVICE'
export const LAYOUT_FOR_MOBILE_DEVICE = 'LAYOUT_FOR_MOBILE_DEVICE'
export const LAYOUT_FOR_EXTRA_LARGER_DEVICE = 'LAYOUT_FOR_EXTRA_LARGER_DEVICE'
export const LOAD_INDIVIDUAL_GRAPH_DATA = 'LOAD_INDIVIDUAL_GRAPH_DATA'
export const RESET_INDIVIDUAL_GRAPH_DATA = 'RESET_INDIVIDUAL_GRAPH_DATA'
export const LOAD_INDIVIDUAL_FILTER_CARD_DATA = 'LOAD_INDIVIDUAL_FILTER_CARD_DATA'
export const RESIZE_REPORT_PAGE = 'RESIZE_REPORT_PAGE';
export const SAVE_DASHBOARD_GRID_ORDER = 'SAVE_DASHBOARD_GRID_ORDER';
export const SAVE_DASHBOARD_FILTER_ORDER = 'SAVE_DASHBOARD_FILTER_ORDER';
export const SAVE_ALL_FILTERS = 'SAVE_ALL_FILTERS';
export const TOGGLE_REFRESH_FOR_ALL_FILTERS = 'TOGGLE_REFRESH_FOR_ALL_FILTERS';
export const LOAD_GROWTH_FACTOR = 'LOAD_GROWTH_FACTOR';
export const SET_REFRESH_TOKENS = 'SET_REFRESH_TOKENS';
export const RESET_REFRESH_TOKENS = 'RESET_REFRESH_TOKENS';
export const SET_STAGES = 'SET_STAGES';
export const SET_REPORT_FILTERS_SEED_DATA = 'SET_REPORT_FILTERS_SEED_DATA';
export const SET_TAB_MODEL = 'SET_TAB_MODEL';
export const SET_SELECTED_TAB = 'SET_SELECTED_TAB';
export const SET_PAGINATION = 'SET_PAGINATION';
export const NAVIGATE_PAGE = 'NAVIGATE_PAGE';
export const CHANGE_PAGES_SIZE = 'CHANGE_PAGES_SIZE';
export const CLONE_GLOBAL_FILTERS = 'CLONE_GLOBAL_FILTERS';
export const TURN_PAGINATION_CONTROL_FLAG = 'TURN_PAGINATION_CONTROL_FLAG';
export const RESET_FILTERS = 'RESET_FILTERS';
export const SET_NAV_LINK = 'SET_NAV_LINK';
export const CLOSE_THE_CARD = 'CLOSE_THE_CARD';
export const SET_IS_DEFAULT_LAYOUT = 'SET_IS_DEFAULT_LAYOUT';
export const SET_SEED_FILTERS = 'SET_SEED_FILTERS';
export const SET_ADDITIONAL_FILTERS = 'SET_ADDITIONAL_FILTERS';
export const SET_STAGED_FILTERS = 'SET_STAGED_FILTERS';
export const MAKE_STAGING_FILTERS_LIVE = 'MAKE_STAGING_FILTERS_LIVE';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const REQUEST_SALES_DUMP = 'REQUEST_SALES_DUMP';
export const CANCEL_SALES_DUMP = 'CANCEL_SALES_DUMP';
export const SET_SALES_DUMP_STATUS = 'CHECK_STATUS_SALES_DUMP';
export const ACTION_ON_SALES_DUMP_STATUS = 'ACTION_ON_SALES_DUMP_STATUS';
export const CLEAR_SALES_DUMP = 'CLEAR_SALES_DUMP';
export const SET_SALES_CHANNELS_INFO = 'SET_SALES_CHANNELS_INFO';
export const SAVE_COMPONENT_SPECIFIC_FILTERS = 'SAVE_COMPONENT_SPECIFIC_FILTERS';
export const SAVE_SEED_FILTER_FOR_DROPDOWNS = 'SAVE_SEED_FILTER_FOR_DROPDOWNS';
export const RESET_SEED_FILTERS_ON_EVENT = 'RESET_SEED_FILTERS_ON_EVENT';

//Orders NINJA
export const ADMIN_SET_NINJA_DASHBOARD_DATA = "ADMIN_SET_NINJA_DASHBOARD_DATA";
export const SET_NINJA_SELECTED_TAB = "SET_NINJA_SELECTED_TAB";
export const SET_NINJA_SEED_FILTERS = "SET_NINJA_SEED_FILTERS";
