//user meta info
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN';
export const SET_USER_LOGGED_OUT = 'SET_USER_LOGGED_OUT';

export const SET_SERVER_DATA = 'SET_SERVER_DATA';
export const SET_USER_VALID = 'SET_USER_VALID';
export const SET_USER_PERMISSIONS = 'SET_USER_PERMISSIONS';
export const SET_ADMIN_PERMISSIONS = 'SET_ADMIN_PERMISSIONS';

//billing
export const SET_CURRENT_ACTIVE_SUBSCRIPTION =
    'SET_CURRENT_ACTIVE_SUBSCRIPTION';
export const SET_COMPANY_MAX_APPLICATIONS_LIMIT =
    'SET_COMPANY_MAX_APPLICATIONS_LIMIT';

export const UPDATE_METRICS = 'UPDATE_METRICS';

//packaging
export const SET_PACKAGING_PRODUCTS = 'SET_PACKAGING_PRODUCTS';
export const SET_CATEGORIES = 'SET_CATEGORIES';

export const SET_EDIT_CATEGORY = 'SET_EDIT_CATEGORY';
export const SET_EDIT_PRODUCT = 'SET_EDIT_PRODUCT';

export const SET_CLEAR_PRODUCT = 'SET_CLEAR_PRODUCT';
export const SET_CLEAR_CATEGORY = 'SET_CLEAR_CATEGORY';

export const SET_L3_CATEGORIES = 'SET_L3_CATEGORIES';
export const SET_L3_DICT = 'SET_L3_DICT';

//variants
export const SET_VARIANTS = 'SET_VARIANTS'
