export const ANALYTICS_FILTER_TYPES = {
    SINGLE_SELECT_DROPDOWN: 'SINGLE_SELECT_DROPDOWN',
    MULTI_SELECT_DROPDOWN: 'MULTI_SELECT_DROPDOWN',
    RADIO_BUTTON: 'RADIO_BUTTON',
    SEARCH_INPUT: 'SEARCH_INPUT',
};

export const FILTER_RETURN_TYPES = {
    [ANALYTICS_FILTER_TYPES.MULTI_SELECT_DROPDOWN]: [],
    [ANALYTICS_FILTER_TYPES.SINGLE_SELECT_DROPDOWN]: '',
    [ANALYTICS_FILTER_TYPES.SEARCH_INPUT]: '',
};
